# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: envName
    displayName: select environment to provision
    default: dev
    values: 
      - dev
      - qa
      - sit
      - uat
      - prod
  - name: TF_operation
    displayName: select TF operation
    default: deploy
    values:
      - Deploy
      - destroy

############
stages:
  - stage: Build
    displayName: TF Build
    jobs:
      - job: Build
        steps: 
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(pipeline.workspace)/s/nsg_2'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)/terraform'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/terraform'
            ArtifactName: 'drop'
            
            publishLocation: 'Container'
            
##########
  - stage: terraform_deploy
    displayName: 'provision ${{parameters.envName}} environment'
    dependsOn: [Build]
    # condition: eq( parameters['TF_operation'] , 'Deploy')
    jobs:
      - job: 
        displayName: provision ${{parameters.envName}} environment
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: download the build arti from CI
            inputs:
               buildType: 'current'
               downloadType: 'single'
               artifactName: 'drop'
               downloadPath: '$(System.ArtifactsDirectory)/terraform'

          - task: TerraformInstaller@1
            displayName: Install terra
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init_hey
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'cicd-terraform-svc-nov22'
              backendAzureRmResourceGroupName: 'ibo-rg'
              backendAzureRmStorageAccountName: 'terradeploy00981'
              backendAzureRmContainerName: 'terracontainer'
              backendAzureRmKey: 'nov22state'
              workingDirectory: '$(System.ArtifactsDirectory)/terraform/drop'
              
          - task: TerraformTaskV4@4
            displayName: validate_hey
            inputs:
               provider: 'azurerm'
               command: 'validate'
               workingDirectory: '$(System.ArtifactsDirectory)/terraform/drop'

          - task: TerraformTaskV4@4
            displayName: plan_hey
            inputs:
               provider: 'azurerm'
               command: 'plan'
               workingDirectory: '$(Pipeline.Workspace)/drop'
               environmentServiceNameAzureRM: $(System.ArtifactsDirectory)/terraform/drop





